# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYIqkGNdAe2SnzmNqiBe-ml9a4w7QbyG
"""

2+3

def ev(n):
  if n%2==0:
    return True
  else:
    return False